version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./postgre_data:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      ./web/
    ports:
      - 127.0.0.1:6565:8000
    environment:
        BOT_TOKEN: ${BOT_TOKEN}
        DB_URL: ${DB_URL}
    restart: always
    depends_on:
      - db
    network_mode: host        
